name: network
description: Network layer for FridgeMate - HTTP client setup
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  
  # ❌ NO domain/data dependencies
  # ❌ NO get_it

dev_dependencies:
  build_runner: ^2.4.0