name: config
description: Configuration layer for FridgeMate - Constants and environment
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.0