name: domain
description: Domain layer for FridgeMate - Pure business logic
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  dartz: ^0.10.1                  # Functional programming
  freezed_annotation: ^2.4.0      # Immutable models
  json_annotation: ^4.8.0
  
  # ❌ NO Flutter dependency!
  # ❌ NO get_it!
  # ❌ NO other modules!

dev_dependencies:
  build_runner: ^2.4.0
  freezed: ^2.4.0
  json_serializable: ^6.7.0