name: local_storage
description: Local storage layer for FridgeMate - Database and preferences
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  
  # ❌ NO domain/data dependencies
  # ❌ NO get_it

dev_dependencies:
  build_runner: ^2.4.0
  drift_dev: ^2.14.0