name: common
description: Common utilities for FridgeMate - Utils, extensions, and constants
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.19.0                    # Date formatting
  path_provider: ^2.1.0           # File operations
  image_picker: ^1.0.0            # Image utilities
  device_info_plus: ^9.1.0        # Device info
  
  # ❌ NO domain/data dependencies
  # ❌ NO get_it

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0