name: common
description: Common utilities for FridgeMate - Utils, extensions, and constants
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # ❌ NO domain/data dependencies
  # ❌ NO get_it

dev_dependencies:
  build_runner: ^2.4.0